### ISSUE TITLE
Fix imports of private-pool to point to prosper-pool

### ISSUE THREAD

**Issue by WhoSoup** [FactomWyomingEntity/prosper-pool#37]
Hey, I assume that the repo was renamed from "private-pool" to "prosper-pool" at some point. All of the imports still point to the "private-pool" repo, ie:

https://github.com/FactomWyomingEntity/prosper-pool/blob/7bea8f469cfbb1725ec9a6a6975f3b63f442c1e7/prosper-miner/main.go#L16-L23

**Comment by Emyrk** [comment]
Yes it was. I'll make a quick update.

**Comment by Emyrk** [comment]
Fixed #38
